// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package test

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "test"
	ScDescription = "test description"
	HScName       = wasmlib.ScHname(0x36208b92)
)

const (
	ParamDescription = "description"
)

const (
	StateTestStructs = "testStructs"
)

const (
	FuncAddTestStruct = "addTestStruct"
	FuncClearAll      = "clearAll"
)

const (
	HFuncAddTestStruct = wasmlib.ScHname(0x9dbe9a07)
	HFuncClearAll      = wasmlib.ScHname(0x7c3a13e7)
)
