// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package test

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type AddTestStructCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableAddTestStructParams
}

type ClearAllCall struct {
	Func    *wasmlib.ScFunc
}

type Funcs struct{}

var ScFuncs Funcs

func (sc Funcs) AddTestStruct(ctx wasmlib.ScFuncCallContext) *AddTestStructCall {
	f := &AddTestStructCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncAddTestStruct)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

func (sc Funcs) ClearAll(ctx wasmlib.ScFuncCallContext) *ClearAllCall {
	return &ClearAllCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncClearAll)}
}
