// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package test

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamDescription = 0


	IdxStateTestStructs = 1
)

const keyMapLen = 2

var keyMap = [keyMapLen]wasmlib.Key{
	ParamDescription,
	StateTestStructs,
}

var idxMap [keyMapLen]wasmlib.Key32
