// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package test

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type ImmutableAddTestStructParams struct {
	id int32
}

func (s ImmutableAddTestStructParams) Description() wasmlib.ScImmutableString {
	return wasmlib.NewScImmutableString(s.id, idxMap[IdxParamDescription])
}

type MutableAddTestStructParams struct {
	id int32
}

func (s MutableAddTestStructParams) Description() wasmlib.ScMutableString {
	return wasmlib.NewScMutableString(s.id, idxMap[IdxParamDescription])
}
