// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package test

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type ArrayOfImmutableTestStruct struct {
	objID int32
}

func (a ArrayOfImmutableTestStruct) Length() int32 {
	return wasmlib.GetLength(a.objID)
}

func (a ArrayOfImmutableTestStruct) GetTestStruct(index int32) ImmutableTestStruct {
	return ImmutableTestStruct{objID: a.objID, keyID: wasmlib.Key32(index)}
}

type ImmutabletestState struct {
	id int32
}

func (s ImmutabletestState) TestStructs() ArrayOfImmutableTestStruct {
	arrID := wasmlib.GetObjectID(s.id, idxMap[IdxStateTestStructs], wasmlib.TYPE_ARRAY|wasmlib.TYPE_BYTES)
	return ArrayOfImmutableTestStruct{objID: arrID}
}

type ArrayOfMutableTestStruct struct {
	objID int32
}

func (a ArrayOfMutableTestStruct) Clear() {
	wasmlib.Clear(a.objID)
}

func (a ArrayOfMutableTestStruct) Length() int32 {
	return wasmlib.GetLength(a.objID)
}

func (a ArrayOfMutableTestStruct) GetTestStruct(index int32) MutableTestStruct {
	return MutableTestStruct{objID: a.objID, keyID: wasmlib.Key32(index)}
}

type MutabletestState struct {
	id int32
}

func (s MutabletestState) TestStructs() ArrayOfMutableTestStruct {
	arrID := wasmlib.GetObjectID(s.id, idxMap[IdxStateTestStructs], wasmlib.TYPE_ARRAY|wasmlib.TYPE_BYTES)
	return ArrayOfMutableTestStruct{objID: arrID}
}
