# Build stage
FROM ubuntu:22.04 AS build
ARG BUILD_TAGS=rocksdb
ARG BUILD_LD_FLAGS="--X=github.com/iotaledger/wasp/components/app.Version=v0.0.0-testing"
ARG GO_VERSION=1.20.4

LABEL org.label-schema.description="Wasp"
LABEL org.label-schema.name="iotaledger/wasp"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.vcs-url="https://github.com/iotaledger/wasp"

RUN apt-get update && \
    apt-get install -y build-essential libstdc++6 software-properties-common make gcc git curl tar

RUN curl -LO https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.20.4.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin

RUN add-apt-repository ppa:ethereum/ethereum && \
    apt-get update && \
    apt-get install -y solc

WORKDIR /

RUN git clone https://github.com/iotaledger/wasp && \
    git clone https://github.com/iotaledger/hornet && \
    git clone https://github.com/iotaledger/inx-indexer && \
    git clone https://github.com/iotaledger/inx-coordinator && \
    git clone https://github.com/iotaledger/inx-faucet

WORKDIR /hornet

RUN go mod download && \
    go mod verify && \
    go build -o /usr/local/bin/ -a -tags=rocksdb -ldflags='-w -s'

WORKDIR /inx-indexer

RUN go mod download && \
    go mod verify && \
    go build -o /usr/local/bin/ -a

WORKDIR /inx-coordinator

RUN go mod download && \
    go mod verify && \
    go build -o /usr/local/bin/ -a

WORKDIR /inx-faucet

RUN go mod download && \
    go mod verify && \
    git submodule update --init --recursive && \
    go build -o /usr/local/bin/ -a

WORKDIR /wasp

RUN go mod download && \
    go mod verify && \
    go build -o /usr/local/bin/ -tags rocksdb -ldflags "-X=github.com/iotaledger/wasp/components/app.Version=v0.0.0-testing" ./tools/schema 

RUN make wasm && \
    make compile-solidity && \
    go build -o /usr/local/bin/ -tags rocksdb -ldflags "-X=github.com/iotaledger/wasp/components/app.Version=v0.0.0-testing" ./...

