# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright: ""
name: timestamp
description: Extremely simple timestamp server
license: Apache-2.0
repository: https://github.com/iotaledger/wasp/contracts/wasm/timestamp
structs: {}
typedefs: {}
state:
funcs:
  now:
views:
  getTimestamp:
    results:
      timestamp: Uint64 # last official timestamp generated
