# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright: ""
name: CoreContracts
description: Tests core contract interfaces
license: Apache-2.0
repository: https://github.com/iotaledger/wasp/contracts/wasm/corecontracts
events: {}
structs: {}
typedefs: {}
state:
funcs:
views:
