# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright: ""
name: CoreContracts
description: Tests core contract interfaces
events: {}
structs: {}
typedefs: {}
state:
funcs:
views:
