# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright: ""
name: memory
description: memory description
license: Apache-2.0
repository: https://github.com/iotaledger/wasp/contracts/wasm/memory
events: {}
structs: {}
typedefs: {}
state:
    owner: AgentID # current owner of this smart contract
funcs:
    f:
        params:
            n: Uint32
views: {}
