# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright: ""
name: storage
description: storage description
events: {}
structs: {}
typedefs: {}
state:
    v: Uint32[]
funcs:
    f:
        params:
            n: Uint32
views: {}
