// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";

export const ScName        = "test";
export const ScDescription = "test description";
export const HScName       = new wasmlib.ScHname(0x36208b92);

export const ParamDescription = "description";

export const StateTestStructs = "testStructs";

export const FuncAddTestStruct = "addTestStruct";
export const FuncClearAll      = "clearAll";

export const HFuncAddTestStruct = new wasmlib.ScHname(0x9dbe9a07);
export const HFuncClearAll      = new wasmlib.ScHname(0x7c3a13e7);
