// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export class AddTestStructCall {
	func: wasmlib.ScFunc = new wasmlib.ScFunc(sc.HScName, sc.HFuncAddTestStruct);
	params: sc.MutableAddTestStructParams = new sc.MutableAddTestStructParams();
}

export class AddTestStructContext {
	params: sc.ImmutableAddTestStructParams = new sc.ImmutableAddTestStructParams();
	state: sc.MutabletestState = new sc.MutabletestState();
}

export class ClearAllCall {
	func: wasmlib.ScFunc = new wasmlib.ScFunc(sc.HScName, sc.HFuncClearAll);
}

export class ClearAllContext {
	state: sc.MutabletestState = new sc.MutabletestState();
}

export class ScFuncs {
    static addTestStruct(ctx: wasmlib.ScFuncCallContext): AddTestStructCall {
        let f = new AddTestStructCall();
        f.func.setPtrs(f.params, null);
        return f;
    }

    static clearAll(ctx: wasmlib.ScFuncCallContext): ClearAllCall {
        return new ClearAllCall();
    }
}
