// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export const IdxParamDescription = 0;


export const IdxStateTestStructs = 1;

export let keyMap: string[] = [
	sc.ParamDescription,
	sc.StateTestStructs,
];

export let idxMap: wasmlib.Key32[] = new Array(keyMap.length);
