// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export class ImmutableAddTestStructParams extends wasmlib.ScMapID {
    description(): wasmlib.ScImmutableString {
		return new wasmlib.ScImmutableString(this.mapID, sc.idxMap[sc.IdxParamDescription]);
	}
}

export class MutableAddTestStructParams extends wasmlib.ScMapID {
    description(): wasmlib.ScMutableString {
		return new wasmlib.ScMutableString(this.mapID, sc.idxMap[sc.IdxParamDescription]);
	}
}
