// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

import * as wasmlib from "wasmlib";
import * as sc from "./index";

export class ArrayOfImmutableTestStruct {
	objID: i32;

    constructor(objID: i32) {
        this.objID = objID;
    }

    length(): i32 {
        return wasmlib.getLength(this.objID);
    }

	getTestStruct(index: i32): sc.ImmutableTestStruct {
		return new sc.ImmutableTestStruct(this.objID, new wasmlib.Key32(index));
	}
}

export class ImmutabletestState extends wasmlib.ScMapID {
    testStructs(): sc.ArrayOfImmutableTestStruct {
		let arrID = wasmlib.getObjectID(this.mapID, sc.idxMap[sc.IdxStateTestStructs], wasmlib.TYPE_ARRAY|wasmlib.TYPE_BYTES);
		return new sc.ArrayOfImmutableTestStruct(arrID);
	}
}

export class ArrayOfMutableTestStruct {
	objID: i32;

    constructor(objID: i32) {
        this.objID = objID;
    }

    clear(): void {
        wasmlib.clear(this.objID);
    }

    length(): i32 {
        return wasmlib.getLength(this.objID);
    }

	getTestStruct(index: i32): sc.MutableTestStruct {
		return new sc.MutableTestStruct(this.objID, new wasmlib.Key32(index));
	}
}

export class MutabletestState extends wasmlib.ScMapID {
    testStructs(): sc.ArrayOfMutableTestStruct {
		let arrID = wasmlib.getObjectID(this.mapID, sc.idxMap[sc.IdxStateTestStructs], wasmlib.TYPE_ARRAY|wasmlib.TYPE_BYTES);
		return new sc.ArrayOfMutableTestStruct(arrID);
	}
}
