# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright: ""
name: HelloWorld
description: The ubiquitous hello world demo
structs: {}
typedefs: {}
state: {}
funcs:
  helloWorld: {}
views:
  getHelloWorld:
    results:
      helloWorld: String
