# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright: ""
name: HelloWorld
description: The ubiquitous hello world demo
license: Apache-2.0
repository: https://github.com/iotaledger/wasp/contracts/wasm/helloworld
structs: {}
typedefs: {}
state: {}
funcs:
  helloWorld: {}
views:
  getHelloWorld:
    results:
      helloWorld: String
