# Copyright 2020 IOTA Stiftung
# SPDX-License-Identifier: Apache-2.0
copyright: ""
name: executiontime
description: executiontime description
license: Apache-2.0
repository: https://github.com/iotaledger/wasp/contracts/wasm/executiontime
events: {}
structs: {}
typedefs: {}
state:
    owner: AgentID # current owner of this smart contract
funcs:
    f:
        params:
            n: Uint32
        results:
            n: Uint32
views:
