name: CoreRoot
description: Root Contract
structs: {}
typedefs: {}
state: {}
funcs: 
  deployContract:
    params:
      programHash=ph: Hash # TODO variable init params for deployed contract
      description=ds: String? # default 'N/A'
      name=nm: String
  grantDeployPermission:
    access: chain # only chain owner can invoke this function
    params:
      deployer=dp: AgentID
  revokeDeployPermission:
    access: chain # only chain owner can invoke this function
    params:
      deployer=dp: AgentID
  requireDeployPermissions:
    access: chain # only chain owner can invoke this function
    params:
      deployPermissionsEnabled=de: Bool
views:
  findContract:
    params:
      hname=hn: Hname
    results:
      contractFound=cf: Bool
      contractRecData=dt: Bytes # encoded contract record
  getContractRecords:
    results:
      contractRegistry=r: map[Hname]Bytes # contract records
