name: Go mod tidy

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: run go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with: 
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      
      - name: Run go mod tidy script
        run: ./scripts/go_mod_tidy.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          committer_email: actions@github.com
          message: 'updated go mod files'
          add: '.'
