# Documentation at http://goreleaser.com

# Project name
project_name: wasp-cli

# Builds
builds:
  # Linux AMD64
  - id: wasp-cli-linux-amd64
    binary: wasp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X=github.com/iotaledger/wasp/core/app.Version={{ .Summary }}
    main: main.go
    dir: ./tools/wasp-cli
    goos:
      - linux
    goarch:
      - amd64

  # Linux ARM64
  - id: wasp-cli-linux-arm64
    binary: wasp-cli
    env:
      - CGO_ENABLED=0
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    ldflags:
      - -s -w -X=github.com/iotaledger/wasp/core/app.Version={{ .Summary }}
    main: main.go
    dir: ./tools/wasp-cli
    goos:
      - linux
    goarch:
      - arm64

  # Windows AMD64
  - id: wasp-cli-windows-amd64
    binary: wasp-cli
    env:
      - CGO_ENABLED=0
      - CC=/usr/bin/x86_64-w64-mingw32-gcc-posix
      - CXX=/usr/bin/x86_64-w64-mingw32-g++-posix
    ldflags:
      - -s -w -X=github.com/iotaledger/wasp/core/app.Version={{ .Summary }}
    main: main.go
    dir: ./tools/wasp-cli
    goos:
      - windows
    goarch:
      - amd64

  # macOS AMD64
  - id: wasp-cli-macos-amd64
    binary: wasp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X=github.com/iotaledger/wasp/core/app.Version={{ .Summary }}
    main: main.go
    dir: ./tools/wasp-cli
    goos:
      - darwin
    goarch:
      - amd64

  # macOS ARM64
  - id: wasp-cli-macos-arm64
    binary: wasp-cli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X=github.com/iotaledger/wasp/core/app.Version={{ .Summary }}
    main: main.go
    dir: ./tools/wasp-cli
    goos:
      - darwin
    goarch:
      - arm64

universal_binaries:
  # macOS ARM64+AMD64 (universal binary)
  - id: wasp-cli-macos-universal
    ids:
      - wasp-cli-macos-amd64
      - wasp-cli-macos-arm64
    # remove the previous single-arch binaries from the artifact list.
    replace: true

# Archives
archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "wasp-cli_{{.Version}}_{{.Os}}_{{.Arch}}"
    replacements:
      amd64: x86_64
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
    files:
      - README.md
      - LICENSE

# Checksum
checksum:
  name_template: "checksums.txt"

# Snapshot
snapshot:
  name_template: "{{ .Tag }}"

# Changelog
changelog:
  skip: true

# Release
release:
  prerelease: auto
  github:
    owner: iotaledger
    name: wasp
